# .github/release.yml
# Controls the "Generate release notes" button output.

changelog:
  # Hide anything that shouldn't appear as "Other changes".
  exclude:
    labels:
      - skip-changelog
      - test
      - wontfix
      - question
      - invalid
      - enhancement
      - help wanted
      - duplicate
      - core team
      - config
    autors:
      - dependabot[bot]
      - renovate[bot]

  categories:
    - title: "New Component 🆕"
      labels:
        - new component

    - title: "New Feature 🚀"
      labels:
        - new feature

    - title: "Bug Fix 🐛"
      labels:
        - bug

    - title: "Refactor ✏️"
      labels:
        - refactor

    - title: "Documentation 📚"
      labels:
        - documentation
        
    - title: "Breaking Changes 💥"
      labels: 
        - breaking changes