module.exports = {
  '1-default-xl': 'var(--effect-1-default-xl)',
  '1-default-lg': 'var(--effect-1-default-lg)',
  '1-default-base': 'var(--effect-1-default-base)',
  '1-default-sm': 'var(--effect-1-default-sm)',
  '1-default-xs': 'var(--effect-1-default-xs)',
  '1-hover-xl': 'var(--effect-1-hover-xl)',
  '1-hover-lg': 'var(--effect-1-hover-lg)',
  '1-hover-base': 'var(--effect-1-hover-base)',
  '1-hover-sm': 'var(--effect-1-hover-sm)',
  '1-hover-xs': 'var(--effect-1-hover-xs)',
  '2-default-xl': 'var(--effect-2-default-xl)',
  '2-default-lg': 'var(--effect-2-default-lg)',
  '2-default-base': 'var(--effect-2-default-base)',
  '2-default-sm': 'var(--effect-2-default-sm)',
  '2-default-xs': 'var(--effect-2-default-xs)',
  '2-hover-xl': 'var(--effect-2-hover-xl)',
  '2-hover-lg': 'var(--effect-2-hover-lg)',
  '2-hover-base': 'var(--effect-2-hover-base)',
  '2-hover-sm': 'var(--effect-2-hover-sm)',
  '2-hover-xs': 'var(--effect-2-hover-xs)',
  'primary-focus': 'var(--primary-focus)',
  'secondary-focus': 'var(--secondary-focus)',
  'info-focus': 'var(--info-focus)',
  'secondary-light-focus': 'var(--secondary-light-focus)',
  'neutral-focus': 'var(--neutral-focus)',
};
