/** See cleave.js documentation https://nosir.github.io/cleave.js */
export interface IInputMaskOptions {
  backspace?: boolean;
  blocks?: number[];
  blocksLength?: number;
  copyDelimiter?: boolean;
  creditCard?: boolean;
  creditCardStrictMode?: boolean;
  creditCardType?: string;
  date?: boolean;
  dateFormatter?: unknown;
  dateMax?: string;
  dateMin?: string;
  datePattern?: string[];
  delimiter?: string;
  delimiterLazyShow?: boolean;
  delimiterLength?: number;
  delimiters?: string[];
  initValue?: string;
  letterOnly?: boolean;
  lowerCase?: boolean;
  maxLength?: number;
  noImmediatePrefix?: boolean;
  numeral?: boolean;
  numeralDecimalMark?: string;
  numeralDecimalScale?: number;
  numeralIntegerScale?: number;
  numeralPositiveOnly?: boolean;
  numeralThousandsGroupStyle?: string;
  numericOnly?: boolean;
  phone?: boolean;
  phoneFormatter?: unknown;
  phoneRegionCode?: string;
  prefix?: string;
  prefixLength?: number;
  rawValueTrimPrefix?: boolean;
  result?: string;
  signBeforePrefix?: boolean;
  stripLeadingZeroes?: boolean;
  swapHiddenInput?: boolean;
  tailPrefix?: boolean;
  time?: boolean;
  timeFormat?: string;
  timeFormatter?: unknown;
  timePattern?: string[];
  uppercase?: boolean;
  regex?: RegExp | string;
}
