module.exports = function ({ addComponents }) {
  addComponents({
    '.title-display-lg': {
      fontFamily: 'var(--mobile-title-display1-font)',
      fontSize: 'var(--mobile-title-display1-size)',
      fontWeight: 'var(--mobile-title-display1-line-weight)',
      lineHeight: 'var(--mobile-title-display1-line-height)',
      letterSpacing: '-4.8px',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-display1-font)',
        fontSize: 'var(--tablet-title-display1-size)',
        fontWeight: 'var(--tablet-title-display1-line-weight)',
        lineHeight: 'var(--tablet-title-display1-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-display1-font)',
        fontSize: 'var(--desktop-title-display1-size)',
        fontWeight: 'var(--desktop-title-display1-line-weight)',
        lineHeight: 'var(--desktop-title-display1-line-height)',
      },
    },
    '.title-display-md': {
      fontFamily: 'var(--mobile-title-display2-font)',
      fontSize: 'var(--mobile-title-display2-size)',
      fontWeight: 'var(--mobile-title-display2-line-weight)',
      lineHeight: 'var(--mobile-title-display2-line-height)',
      letterSpacing: '-4.8px',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-display2-font)',
        fontSize: 'var(--tablet-title-display2-size)',
        fontWeight: 'var(--tablet-title-display2-line-weight)',
        lineHeight: 'var(--tablet-title-display2-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-display2-font)',
        fontSize: 'var(--desktop-title-display2-size)',
        fontWeight: 'var(--desktop-title-display2-line-weight)',
        lineHeight: 'var(--desktop-title-display2-line-height)',
      },
    },
    '.title-h1': {
      fontFamily: 'var(--mobile-title-h1-font)',
      fontSize: 'var(--mobile-title-h1-size)',
      fontWeight: 'var(--mobile-title-h1-line-weight)',
      lineHeight: 'var(--mobile-title-h1-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h1-font)',
        fontSize: 'var(--tablet-title-h1-size)',
        fontWeight: 'var(--tablet-title-h1-line-weight)',
        lineHeight: 'var(--tablet-title-h1-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h1-font)',
        fontSize: 'var(--desktop-title-h1-size)',
        fontWeight: 'var(--desktop-title-h1-line-weight)',
        lineHeight: 'var(--desktop-title-h1-line-height)',
      },
    },
    '.title-h2': {
      fontFamily: 'var(--mobile-title-h2-font)',
      fontSize: 'var(--mobile-title-h2-size)',
      fontWeight: 'var(--mobile-title-h2-line-weight)',
      lineHeight: 'var(--mobile-title-h2-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h2-font)',
        fontSize: 'var(--tablet-title-h2-size)',
        fontWeight: 'var(--tablet-title-h2-line-weight)',
        lineHeight: 'var(--tablet-title-h2-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h2-font)',
        fontSize: 'var(--desktop-title-h2-size)',
        fontWeight: 'var(--desktop-title-h2-line-weight)',
        lineHeight: 'var(--desktop-title-h2-line-height)',
      },
    },
    '.title-h3': {
      fontFamily: 'var(--mobile-title-h3-font)',
      fontSize: 'var(--mobile-title-h3-size)',
      fontWeight: 'var(--mobile-title-h3-line-weight)',
      lineHeight: 'var(--mobile-title-h3-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h3-font)',
        fontSize: 'var(--tablet-title-h3-size)',
        fontWeight: 'var(--tablet-title-h3-line-weight)',
        lineHeight: 'var(--tablet-title-h3-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h3-font)',
        fontSize: 'var(--desktop-title-h3-size)',
        fontWeight: 'var(--desktop-title-h3-line-weight)',
        lineHeight: 'var(--desktop-title-h3-line-height)',
      },
    },
    '.title-h4': {
      fontFamily: 'var(--mobile-title-h4-font)',
      fontSize: 'var(--mobile-title-h4-size)',
      fontWeight: 'var(--mobile-title-h4-line-weight)',
      lineHeight: 'var(--mobile-title-h4-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h4-font)',
        fontSize: 'var(--tablet-title-h4-size)',
        fontWeight: 'var(--tablet-title-h4-line-weight)',
        lineHeight: 'var(--tablet-title-h4-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h4-font)',
        fontSize: 'var(--desktop-title-h4-size)',
        fontWeight: 'var(--desktop-title-h4-line-weight)',
        lineHeight: 'var(--desktop-title-h4-line-height)',
      },
    },
    '.title-h5': {
      fontFamily: 'var(--mobile-title-h5-font)',
      fontSize: 'var(--mobile-title-h5-size)',
      fontWeight: 'var(--mobile-title-h5-line-weight)',
      lineHeight: 'var(--mobile-title-h5-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h5-font)',
        fontSize: 'var(--tablet-title-h5-size)',
        fontWeight: 'var(--tablet-title-h5-line-weight)',
        lineHeight: 'var(--tablet-title-h5-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h5-font)',
        fontSize: 'var(--desktop-title-h5-size)',
        fontWeight: 'var(--desktop-title-h5-line-weight)',
        lineHeight: 'var(--desktop-title-h5-line-height)',
      },
    },
    '.title-h6': {
      fontFamily: 'var(--mobile-title-h6-font)',
      fontSize: 'var(--mobile-title-h6-size)',
      fontWeight: 'var(--mobile-title-h6-line-weight)',
      lineHeight: 'var(--mobile-title-h6-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-title-h6-font)',
        fontSize: 'var(--tablet-title-h6-size)',
        fontWeight: 'var(--tablet-title-h6-line-weight)',
        lineHeight: 'var(--tablet-title-h6-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-title-h6-font)',
        fontSize: 'var(--desktop-title-h6-size)',
        fontWeight: 'var(--desktop-title-h6-line-weight)',
        lineHeight: 'var(--desktop-title-h6-line-height)',
      },
    },
    '.body-2xl': {
      fontFamily: 'var(--mobile-body-2xl-font)',
      fontSize: 'var(--mobile-body-2xl-size)',
      fontWeight: 'var(--mobile-body-2xl-line-weight)',
      lineHeight: 'var(--mobile-body-2xl-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-2xl-font)',
        fontSize: 'var(--tablet-body-2xl-size)',
        fontWeight: 'var(--tablet-body-2xl-line-weight)',
        lineHeight: 'var(--tablet-body-2xl-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-2xl-font)',
        fontSize: 'var(--desktop-body-2xl-size)',
        fontWeight: 'var(--desktop-body-2xl-line-weight)',
        lineHeight: 'var(--desktop-body-2xl-line-height)',
      },
    },
    '.body-xl': {
      fontFamily: 'var(--mobile-body-xl-font)',
      fontSize: 'var(--mobile-body-xl-size)',
      fontWeight: 'var(--mobile-body-xl-line-weight)',
      lineHeight: 'var(--mobile-body-xl-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-xl-font)',
        fontSize: 'var(--tablet-body-xl-size)',
        fontWeight: 'var(--tablet-body-xl-line-weight)',
        lineHeight: 'var(--tablet-body-xl-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-xl-font)',
        fontSize: 'var(--desktop-body-xl-size)',
        fontWeight: 'var(--desktop-body-xl-line-weight)',
        lineHeight: 'var(--desktop-body-xl-line-height)',
      },
    },
    '.body-lg': {
      fontFamily: 'var(--mobile-body-l-font)',
      fontSize: 'var(--mobile-body-l-size)',
      fontWeight: 'var(--mobile-body-l-line-weight)',
      lineHeight: 'var(--mobile-body-l-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-l-font)',
        fontSize: 'var(--tablet-body-l-size)',
        fontWeight: 'var(--tablet-body-l-line-weight)',
        lineHeight: 'var(--tablet-body-l-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-l-font)',
        fontSize: 'var(--desktop-body-l-size)',
        fontWeight: 'var(--desktop-body-l-line-weight)',
        lineHeight: 'var(--desktop-body-l-line-height)',
      },
    },
    '.body-base': {
      fontFamily: 'var(--mobile-body-m-base-font)',
      fontSize: 'var(--mobile-body-m-base-size)',
      fontWeight: 'var(--mobile-body-m-base-line-weight)',
      lineHeight: 'var(--mobile-body-m-base-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-m-base-font)',
        fontSize: 'var(--tablet-body-m-base-size)',
        fontWeight: 'var(--tablet-body-m-base-line-weight)',
        lineHeight: 'var(--tablet-body-m-base-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-m-base-font)',
        fontSize: 'var(--desktop-body-m-base-size)',
        fontWeight: 'var(--desktop-body-m-base-line-weight)',
        lineHeight: 'var(--desktop-body-m-base-line-height)',
      },
    },
    '.body-sm': {
      fontFamily: 'var(--mobile-body-s-font)',
      fontSize: 'var(--mobile-body-s-size)',
      fontWeight: 'var(--mobile-body-s-line-weight)',
      lineHeight: 'var(--mobile-body-s-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-s-font)',
        fontSize: 'var(--tablet-body-s-size)',
        fontWeight: 'var(--tablet-body-s-line-weight)',
        lineHeight: 'var(--tablet-body-s-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-s-font)',
        fontSize: 'var(--desktop-body-s-size)',
        fontWeight: 'var(--desktop-body-s-line-weight)',
        lineHeight: 'var(--desktop-body-s-line-height)',
      },
    },
    '.body-xs': {
      fontFamily: 'var(--mobile-body-xs-font)',
      fontSize: 'var(--mobile-body-xs-size)',
      fontWeight: 'var(--mobile-body-xs-line-weight)',
      lineHeight: 'var(--mobile-body-xs-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-xs-font)',
        fontSize: 'var(--tablet-body-xs-size)',
        fontWeight: 'var(--tablet-body-xs-line-weight)',
        lineHeight: 'var(--tablet-body-xs-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-xs-font)',
        fontSize: 'var(--desktop-body-xs-size)',
        fontWeight: 'var(--desktop-body-xs-line-weight)',
        lineHeight: 'var(--desktop-body-xs-line-height)',
      },
    },
    '.body-2xs': {
      fontFamily: 'var(--mobile-body-2xs-font)',
      fontSize: 'var(--mobile-body-2xs-size)',
      fontWeight: 'var(--mobile-body-2xs-line-weight)',
      lineHeight: 'var(--mobile-body-2xs-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-body-2xs-font)',
        fontSize: 'var(--tablet-body-2xs-size)',
        fontWeight: 'var(--tablet-body-2xs-line-weight)',
        lineHeight: 'var(--tablet-body-2xs-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-body-2xs-font)',
        fontSize: 'var(--desktop-body-2xs-size)',
        fontWeight: 'var(--desktop-body-2xs-line-weight)',
        lineHeight: 'var(--desktop-body-2xs-line-height)',
      },
    },
    '.subheading-base': {
      fontFamily: 'var(--mobile-subheading-m-base-font)',
      fontSize: 'var(--mobile-subheading-m-base-size)',
      fontWeight: 'var(--mobile-subheading-m-base-line-weight)',
      lineHeight: 'var(--mobile-subheading-m-base-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-subheading-m-base-font)',
        fontSize: 'var(--tablet-subheading-m-base-size)',
        fontWeight: 'var(--tablet-subheading-m-base-line-weight)',
        lineHeight: 'var(--tablet-subheading-m-base-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-subheading-m-base-font)',
        fontSize: 'var(--desktop-subheading-m-base-size)',
        fontWeight: 'var(--desktop-subheading-m-base-line-weight)',
        lineHeight: 'var(--desktop-subheading-m-base-line-height)',
      },
    },
    '.subheading-sm': {
      fontFamily: 'var(--mobile-subheading-s-font)',
      fontSize: 'var(--mobile-subheading-s-size)',
      fontWeight: 'var(--mobile-subheading-s-line-weight)',
      lineHeight: 'var(--mobile-subheading-s-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-subheading-s-font)',
        fontSize: 'var(--tablet-subheading-s-size)',
        fontWeight: 'var(--tablet-subheading-s-line-weight)',
        lineHeight: 'var(--tablet-subheading-s-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-subheading-s-font)',
        fontSize: 'var(--desktop-subheading-s-size)',
        fontWeight: 'var(--desktop-subheading-s-line-weight)',
        lineHeight: 'var(--desktop-subheading-s-line-height)',
      },
    },
    '.subheading-xs': {
      fontFamily: 'var(--mobile-subheading-xs-font)',
      fontSize: 'var(--mobile-subheading-xs-size)',
      fontWeight: 'var(--mobile-subheading-xs-line-weight)',
      lineHeight: 'var(--mobile-subheading-xs-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-subheading-xs-font)',
        fontSize: 'var(--tablet-subheading-xs-size)',
        fontWeight: 'var(--tablet-subheading-xs-line-weight)',
        lineHeight: 'var(--tablet-subheading-xs-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-subheading-xs-font)',
        fontSize: 'var(--desktop-subheading-xs-size)',
        fontWeight: 'var(--desktop-subheading-xs-line-weight)',
        lineHeight: 'var(--desktop-subheading-xs-line-height)',
      },
    },
    '.subheading-2xs': {
      fontFamily: 'var(--mobile-subheading-2xs-font)',
      fontSize: 'var(--mobile-subheading-2xs-size)',
      fontWeight: 'var(--mobile-subheading-2xs-line-weight)',
      lineHeight: 'var(--mobile-subheading-2xs-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-subheading-2xs-font)',
        fontSize: 'var(--tablet-subheading-2xs-size)',
        fontWeight: 'var(--tablet-subheading-2xs-line-weight)',
        lineHeight: 'var(--tablet-subheading-2xs-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-subheading-2xs-font)',
        fontSize: 'var(--desktop-subheading-2xs-size)',
        fontWeight: 'var(--desktop-subheading-2xs-line-weight)',
        lineHeight: 'var(--desktop-subheading-2xs-line-height)',
      },
    },
    '.label-lg': {
      fontFamily: 'var(--mobile-label-l-font)',
      fontSize: 'var(--mobile-label-l-size)',
      fontWeight: 'var(--mobile-label-l-line-weight)',
      lineHeight: 'var(--mobile-label-l-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-l-font)',
        fontSize: 'var(--tablet-label-l-size)',
        fontWeight: 'var(--tablet-label-l-line-weight)',
        lineHeight: 'var(--tablet-label-l-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-l-font)',
        fontSize: 'var(--desktop-label-l-size)',
        fontWeight: 'var(--desktop-label-l-line-weight)',
        lineHeight: 'var(--desktop-label-l-line-height)',
      },
    },
    '.label-base': {
      fontFamily: 'var(--mobile-label-m-base-font)',
      fontSize: 'var(--mobile-label-m-base-size)',
      fontWeight: 'var(--mobile-label-m-base-line-weight)',
      lineHeight: 'var(--mobile-label-m-base-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-m-base-font)',
        fontSize: 'var(--tablet-label-m-base-size)',
        fontWeight: 'var(--tablet-label-m-base-line-weight)',
        lineHeight: 'var(--tablet-label-m-base-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-m-base-font)',
        fontSize: 'var(--desktop-label-m-base-size)',
        fontWeight: 'var(--desktop-label-m-base-line-weight)',
        lineHeight: 'var(--desktop-label-m-base-line-height)',
      },
    },
    '.label-sm': {
      fontFamily: 'var(--mobile-label-s-font)',
      fontSize: 'var(--mobile-label-s-size)',
      fontWeight: 'var(--mobile-label-s-line-weight)',
      lineHeight: 'var(--mobile-label-s-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-s-font)',
        fontSize: 'var(--tablet-label-s-size)',
        fontWeight: 'var(--tablet-label-s-line-weight)',
        lineHeight: 'var(--tablet-label-s-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-s-font)',
        fontSize: 'var(--desktop-label-s-size)',
        fontWeight: 'var(--desktop-label-s-line-weight)',
        lineHeight: 'var(--desktop-label-s-line-height)',
      },
    },
    '.label-underline-sm': {
      fontFamily: 'var(--mobile-label-underline-s-font)',
      fontSize: 'var(--mobile-label-underline-s-size)',
      fontWeight: 'var(--mobile-label-underline-s-line-weight)',
      lineHeight: 'var(--mobile-label-underline-s-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-underline-s-font)',
        fontSize: 'var(--tablet-label-underline-s-size)',
        fontWeight: 'var(--tablet-label-underline-s-line-weight)',
        lineHeight: 'var(--tablet-label-underline-s-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-underline-s-font)',
        fontSize: 'var(--desktop-label-underline-s-size)',
        fontWeight: 'var(--desktop-label-underline-s-line-weight)',
        lineHeight: 'var(--desktop-label-underline-s-line-height)',
      },
    },
    '.label-underline-base': {
      fontFamily: 'var(--mobile-label-underline-m-base-font)',
      fontSize: 'var(--mobile-label-underline-m-base-size)',
      fontWeight: 'var(--mobile-label-underline-m-base-line-weight)',
      lineHeight: 'var(--mobile-label-underline-m-base-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-underline-m-base-font)',
        fontSize: 'var(--tablet-label-underline-m-base-size)',
        fontWeight: 'var(--tablet-label-underline-m-base-line-weight)',
        lineHeight: 'var(--tablet-label-underline-m-base-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-underline-m-base-font)',
        fontSize: 'var(--desktop-label-underline-m-base-size)',
        fontWeight: 'var(--desktop-label-underline-m-base-line-weight)',
        lineHeight: 'var(--desktop-label-underline-m-base-line-height)',
      },
    },
    '.label-underline-lg': {
      fontFamily: 'var(--mobile-label-underline-l-font)',
      fontSize: 'var(--mobile-label-underline-l-size)',
      fontWeight: 'var(--mobile-label-underline-l-line-weight)',
      lineHeight: 'var(--mobile-label-underline-l-line-height)',
      '@media (min-width: 905px)': {
        fontFamily: 'var(--tablet-label-underline-l-font)',
        fontSize: 'var(--tablet-label-underline-l-size)',
        fontWeight: 'var(--tablet-label-underline-l-line-weight)',
        lineHeight: 'var(--tablet-label-underline-l-line-height)',
      },
      '@media (min-width: 1248px)': {
        fontFamily: 'var(--desktop-label-underline-l-font)',
        fontSize: 'var(--desktop-label-underline-l-size)',
        fontWeight: 'var(--desktop-label-underline-l-line-weight)',
        lineHeight: 'var(--desktop-label-underline-l-line-height)',
      },
    },
  });
};
