/**
 * @fileoverview Auto-generated barrel file for all component interfaces
 *
 * This file is automatically generated by scripts/generate-interfaces.js
 */

// ============================================================================
// Global Interfaces
// ============================================================================
export type { IBadgeOptions } from './global/interfaces/IBadgeOptions';
export type { IIconOptions, IMultiIconOptions } from './global/interfaces/IIconOptions';
export type { ITooltipOptions } from './global/interfaces/ITooltipOptions';

// ============================================================================
// Component Interfaces and Types
// ============================================================================

// tk-accordion
export type { IAccordionItemSelect } from './components/tk-accordion/interfaces';

// tk-alert
export type { IAlertActionButton } from './components/tk-alert/interfaces';

// tk-breadcrumb
export type { IBreadcrumbModel } from './components/tk-breadcrumb/interfaces';

// tk-chips
export type { IChipOptions } from './components/tk-chips/interfaces';

// tk-currency-input
export type { ICurrency, CurrencyInputChangeEvent, Separator } from './components/tk-currency-input/interfaces';

// tk-datepicker
export type { IDateSelection } from './components/tk-datepicker/interfaces';

// tk-editor
export type { HeadingLevel, TkEditorToolbarButtonBehavior, TkEditorDefaultButton, TkEditorCustomButton, TkEditorToolbarConfig } from './components/tk-editor/interfaces';

// tk-gantt-chart
export type {
  IGanttTaskSegment,
  IGanttTask,
  GanttViewType,
  GanttSecondaryHeaderMode,
  GanttWeekStartDay,
  IGanttIndicator,
  IGanttHoliday,
  IGanttColumn,
  GanttTooltipFunction,
  GanttTaskBarFunction,
  IGanttHeaderCell,
  IGanttFlatRow,
} from './components/tk-gantt-chart/interfaces';

// tk-input
export type { IInputMaskOptions } from './components/tk-input/interfaces';

// tk-phone-input
export type { ICountry, IPhoneInputValue } from './components/tk-phone-input/interfaces';

// tk-stepper
export type { IStep, IStepClickDetail } from './components/tk-stepper/interfaces';

// tk-table
export type {
  ITableColumn,
  IFilterOption,
  ITableSort,
  ITableRequest,
  ITableFilter,
  ITableCellEdit,
  ITableExportOptions,
  ITableExportExcelColumn,
  ITableGroup,
} from './components/tk-table/interfaces';

// tk-timeline
export type { ITimelineItem } from './components/tk-timeline/interfaces';

// tk-treeview
export type { ITreeItem } from './components/tk-treeview/interfaces';
