// Demo data for TkTable covering all column fields used in Table.tsx
// Each row contains: id, name, surname {key,value}, age, avatar, country, date,
// status, priority, score, followUp, flag, action (unused), choice, note, email, city, website,
// and data1..data3 for expanded row content.

const dummyData = [
  {
    id: '1',
    name: 'Harun',
    surname: { key: 'surname', value: 'Demir' },
    age: 29,
    avatar: 'value 1',
    country: 'Text here 1',
    date: '2024-01-02',
    status: true,
    priority: 'high',
    score: 92,
    followUp: '2024-01-29',
    flag: true,
    choice: 'yes',
    note: 'Followed by phone',
    email: 'harun@example.com',
    city: 'Istanbul',
    website: 'https://takeoffui.com',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '2',
    name: 'Serkan',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 2',
    country: 'Text here 2',
    date: '2024-01-02',
    status: false,
    priority: 'medium',
    score: 75,
    followUp: '2024-02-10',
    flag: false,
    choice: 'no',
    note: 'Waiting reply',
    email: 'serkan@example.com',
    city: 'Ankara',
    website: 'https://example.com',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '3',
    name: 'Harun',
    surname: { key: 'surname', value: 'Demir' },
    age: 31,
    avatar: 'value 3',
    country: 'Text here 3',
    date: '2024-01-02',
    status: true,
    priority: 'low',
    score: 64,
    followUp: '2024-02-05',
    flag: false,
    choice: 'yes',
    note: '',
    email: 'harun31@example.com',
    city: 'Izmir',
    website: 'https://takeoffui.com/docs',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '4',
    name: 'Zeki',
    surname: { key: 'surname', value: 'Demir' },
    age: 28,
    avatar: 'value 1',
    country: 'Text here 4',
    date: '2024-01-02',
    status: false,
    priority: 'high',
    score: 80,
    followUp: '2024-03-01',
    flag: true,
    choice: 'no',
    note: 'Escalated',
    email: 'zeki@example.com',
    city: 'Bursa',
    website: 'https://bursa.gov.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '5',
    name: 'Harun',
    surname: { key: 'surname', value: 'Demir' },
    age: 31,
    avatar: 'value 2',
    country: 'Text here 5',
    date: '2024-01-02',
    status: true,
    priority: 'medium',
    score: 55,
    followUp: '2024-02-20',
    flag: false,
    choice: 'yes',
    note: '',
    email: 'harun.31@example.com',
    city: 'Eskisehir',
    website: 'https://eskisehir.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '6',
    name: 'Serkan',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 3',
    country: 'Text here 6',
    date: '2024-01-02',
    status: false,
    priority: 'low',
    score: 48,
    followUp: '2024-02-08',
    flag: false,
    choice: 'no',
    note: 'N/A',
    email: 'serkan23@example.com',
    city: 'Antalya',
    website: 'https://antalya.com',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '7',
    name: 'Zeki',
    surname: { key: 'surname', value: 'Demir' },
    age: 28,
    avatar: 'value 1',
    country: 'Text here 7',
    date: '2024-01-02',
    status: true,
    priority: 'high',
    score: 88,
    followUp: '2024-01-20',
    flag: true,
    choice: 'yes',
    note: 'Confirmed',
    email: 'zeki28@example.com',
    city: 'Konya',
    website: 'https://konya.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '8',
    name: 'Rukiye',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 2',
    country: 'Text here 8',
    date: '2024-01-02',
    status: false,
    priority: 'medium',
    score: 67,
    followUp: '2024-03-05',
    flag: false,
    choice: 'no',
    note: '—',
    email: 'rukiye@example.com',
    city: 'Samsun',
    website: 'https://samsun.gov.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '9',
    name: 'Harun',
    surname: { key: 'surname', value: 'Demir' },
    age: 29,
    avatar: 'value 1',
    country: 'Text here 9',
    date: '2024-01-02',
    status: true,
    priority: 'low',
    score: 71,
    followUp: '2024-04-01',
    flag: false,
    choice: 'yes',
    note: '',
    email: 'harun29@example.com',
    city: 'Mersin',
    website: 'https://mersin.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '10',
    name: 'Beytullah',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 2',
    country: 'Text here 10',
    date: '2024-01-02',
    status: false,
    priority: 'high',
    score: 59,
    followUp: '2024-02-25',
    flag: true,
    choice: 'no',
    note: 'Pending',
    email: 'beytullah@example.com',
    city: 'Kayseri',
    website: 'https://kayseri.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '11',
    name: 'Rukiye',
    surname: { key: 'surname', value: 'Demir' },
    age: 31,
    avatar: 'value 3',
    country: 'Text here 11',
    date: '2024-01-02',
    status: true,
    priority: 'medium',
    score: 84,
    followUp: '2024-05-10',
    flag: false,
    choice: 'yes',
    note: 'Reviewed',
    email: 'rukiye31@example.com',
    city: 'Adana',
    website: 'https://adana.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '12',
    name: 'Zeliha',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 1',
    country: 'Text here 12',
    date: '2024-01-02',
    status: false,
    priority: 'low',
    score: 46,
    followUp: '2024-03-18',
    flag: false,
    choice: 'no',
    note: '',
    email: 'zeliha@example.com',
    city: 'Trabzon',
    website: 'https://trabzon.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '13',
    name: 'Harun',
    surname: { key: 'surname', value: 'Demir' },
    age: 29,
    avatar: 'value 2',
    country: 'Text here 13',
    date: '2024-01-02',
    status: true,
    priority: 'high',
    score: 90,
    followUp: '2024-02-14',
    flag: true,
    choice: 'yes',
    note: 'VIP',
    email: 'harun-vip@example.com',
    city: 'Gaziantep',
    website: 'https://gaziantep.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '14',
    name: 'Beytullah',
    surname: { key: 'surname', value: 'Demir' },
    age: 23,
    avatar: 'value 3',
    country: 'Text here 14',
    date: '2024-01-02',
    status: false,
    priority: 'medium',
    score: 61,
    followUp: '2024-04-07',
    flag: false,
    choice: 'no',
    note: '',
    email: 'beytullah23@example.com',
    city: 'Kocaeli',
    website: 'https://kocaeli.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
  {
    id: '15',
    name: 'Rukiye',
    surname: { key: 'surname', value: 'Demir' },
    age: 31,
    avatar: 'value 1',
    country: 'Text here 15',
    date: '2024-01-02',
    status: true,
    priority: 'low',
    score: 73,
    followUp: '2024-01-30',
    flag: true,
    choice: 'yes',
    note: 'OK',
    email: 'rukiye.ok@example.com',
    city: 'Sakarya',
    website: 'https://sakarya.bel.tr',
    data1: 'value 1',
    data2: 'value 2',
    data3: 'value 3',
  },
];

export default dummyData;
